# Generated by Django 3.1.1 on 2020-09-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_subscription', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailContactTranslation',
        ),
    ]
