"""
Django settings for myshop project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from braintree import Configuration, Environment
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'w*e--!t%eo9&!v($oi#2x3gq6j^j=b6=e(wo$u26z@j+=u454u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'shop.apps.ShopConfig',
    'cart.apps.CartConfig',
    'compare.apps.CompareConfig',
    'orders.apps.OrdersConfig',
    'payment.apps.PaymentConfig',
    'coupons.apps.CouponsConfig',
    'email_subscription.apps.EmailSubscriptionConfig',
    'rosetta',
    'parler',
    'localflavor',
    'currencies',
    'django.contrib.postgres',
    'cloudinary',
]



MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


OPENEXCHANGERATES_APP_ID = "c2b2efcb306e075d9c2f2d0b614119ea"

ROOT_URLCONF = 'myshop.urls'

REDIS_HOST = 'ec2-54-91-25-109.compute-1.amazonaws.com'
REDIS_PORT =  14729
REDIS_PASSWORD = 'p3f99a910cb8689f6f5622ec24a4303af307bed1c187ca0512f0b9bd87803bdec'
REDIS_USER = 'h'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'cart.context_processors.cart',
                'django.contrib.messages.context_processors.messages',
                'currencies.context_processors.currencies',
            ],
        },
    },
]

WSGI_APPLICATION = 'myshop.wsgi.application'

CELERY_BROKER_URL = 'amqps://cmtjfjxf:MxPBcqiEZifOJl2aEasLUdUg7104Nsfy@finch.rmq.cloudamqp.com/cmtjfjxf'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'd1pd57lt7pjsk2',
        'USER': 'nurdfswwxralys',
        'PASSWORD': 'c6d206e10ed078492b380606c619aa19da8a4d085e96623fc3ef129c06e2b868',
        'HOST': 'ec2-3-215-207-12.compute-1.amazonaws.com',
        'PORT': '5432'
    }
}

# Braintree settings
BRAINTREE_MERCHANT_ID = 'sby9vj5c6jhf2hr6'
BRAINTREE_PUBLIC_KEY = 'w48k5cjrtdh6zw9d' # Merchant ID
# Public Key
BRAINTREE_PRIVATE_KEY = '9f5ea399e5fd3af0c60fc55ba0bc4837' # Private key
Configuration.configure(
    Environment.Sandbox,
    BRAINTREE_MERCHANT_ID,
    BRAINTREE_PUBLIC_KEY,
    BRAINTREE_PRIVATE_KEY
)

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

PARLER_LANGUAGES = {
    None: (
        {'code': 'en'},
        {'code': 'es'},
        {'code': 'fa'},
    ),
    'default': {
        'fallback': 'en',
        'hide_untranslated': False,
    }
}

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'mrkarami24251@gmail.com'
EMAIL_HOST_PASSWORD = 'moreka75'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
CART_SESSION_ID = 'cart'
COMPARE_SESSION_ID = 'compare'

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en'
LANGUAGES = (
    ('en', _('English')),
    ('es', _('Spanish')),
    ('fa', _('Persian')),
)

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

ADMINS = (
    ('Mohammadreza karami', 'mohammadreza.karami22@yahoo.com.com'),
)

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dt0x3ff8y',
    'API_KEY': '842463339847471',
    'API_SECRET': 'd4CUuUKhO4JSVfy9DA41a4KhGGw',
}
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_ROOT = 'staticfiles'
STATIC_URL = '/static/'

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale/'),
)

DEFAULT_CURRENCY ='USD'