# Generated by Django 3.0.4 on 2020-08-06 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_product_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='valid_from',
        ),
    ]
