# Generated by Django 3.0.4 on 2020-08-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_product_valid_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='valid_to',
            field=models.DateField(null=True),
        ),
    ]
