# Generated by Django 3.0.4 on 2020-08-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200806_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
    ]
