# Generated by Django 3.0.4 on 2020-08-13 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_hotdeal_valid_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='HotDeal',
        ),
    ]
