# Generated by Django 3.0.4 on 2020-08-13 19:32

from django.db import migrations, models
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_product_hotdeal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d/%h/%m/%s')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
