# Generated by Django 3.0.4 on 2020-09-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_feature_featuretranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuretranslation',
            name='feature',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
