# Generated by Django 3.1.1 on 2020-09-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_emailcontact_emailcontacttranslation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailcontacttranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='emailcontacttranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='EmailContact',
        ),
        migrations.DeleteModel(
            name='EmailContactTranslation',
        ),
    ]
