# Generated by Django 3.0.4 on 2020-08-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_product_valid_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='HotDeal_valid_to',
            field=models.DateField(null=True),
        ),
    ]
