# Generated by Django 3.0.4 on 2020-08-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_product_hotdeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='HotDeal',
            field=models.BooleanField(default=False),
        ),
    ]
