# Generated by Django 3.0.4 on 2020-08-13 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20200813_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='mainimage',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='shop.Product'),
        ),
    ]
