# Generated by Django 3.0.4 on 2020-09-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200726_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='iran', max_length=100, verbose_name='city'),
        ),
    ]
