# Generated by Django 3.1.1 on 2020-09-18 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discountOff',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
