# Generated by Django 3.1.1 on 2020-09-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_discountoff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discountOff',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
